# GLOBAL CONFIGURATION
spring:
    # if you want to set a different profile
    # use environment variable:
    #
    # SPRING_PROFILES_ACTIVE=docker
    profiles.active: local
    application.name: Zuul


---
# LOCAL CONFIGURATION
spring:
    profiles: local

server.port: 8082


zuul:
  ignoredServices: '*'
  routes:
    user:
      path: /api/user_service/**
      url: http://localhost:8870/
#      sensitiveHeaders: 
      add-proxy-headers: true
    admin:
      path: /api/admin_service/**
      url: http://localhost:39146/
#      sensitiveHeaders: 
      add-proxy-headers: true


      
security:
  oauth2:
    client:
      clientId: openIdDemo
      clientSecret: f33048d1-82be-42de-81d9-71356ab8b19d
      accessTokenUri: http://localhost:8080/auth/realms/demo/protocol/openid-connect/token
      userAuthorizationUri: http://localhost:8080/auth/realms/demo/protocol/openid-connect/auth
    resource:
      jwt:
        key-value: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlsteeVtC+LlM/uhuusceFDvKbeCPolBEpq+rNnRbBvSPDCdKGcIIpjrQswX/58loE/bQ45A5IY1Tlm1MWbGxZ0IZhYaILeTNySTK3aRsV94OpN+ib/PGWkP1aQZ6wdm4//C6whOhCbulbLwSTyjByD72FGdaO/OhrATD9OAEcP0QmrvjLRHQBA80lxB4fRCyIrea9aL/AuvBsAbTz1Ub70rH8ydwaPtev7/L4dY+9NaqoL23pLIYyV7k3cuPeyHU/lt4I68R4rNiFv08zQFWGMr+li13cWNi9KsNfP5h6Ce7h+D2WmOUv7Tm9b8rAJ4jGHuf8ylHWt0SQxBtofuldwIDAQAB
  sessions: ALWAYS

endpoints.routes.sensitive: false
       
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG      
      
---
# DOCKER CONFIGURATION
spring:
    profiles: docker
---
# NO-SECURITY CONFIGURATION
spring:
    profiles: no-security
    h2.console.enabled: true

security.ignored: /**    

server.port: 8082


      
---
# OPENSHIFT CONFIGURATION
spring:
    profiles: openshift
    h2.console.enabled: true

security.ignored: /**    

server.port: 8080

# zuul routes
zuul:
  ignoredServices: '*'
  routes:
    user:
      path: /api/user_service/**
      url: http://user-service:8080/
#      sensitiveHeaders: 
      add-proxy-headers: true
    admin:
      path: /api/admin_service/**
      url: http://admin-service:8080/
#      sensitiveHeaders: 
      add-proxy-headers: true 