# GLOBAL CONFIGURATION
spring:
    # if you want to set a different profile
    # use environment variable:
    #
    # SPRING_PROFILES_ACTIVE=docker
    profiles.active: local
    application.name: Zuul

# zuul proxy exposes 8082
server.port: 8082

# zuul routes
zuul:
  ignoredServices: '*'
  routes:
    user:
      path: /user_service/**
      url: http://localhost:8870/
      sensitiveHeaders: 
      add-proxy-headers: true
    admin:
      path: /admin_service/**
      url: http://localhost:39146/
      sensitiveHeaders: 
      add-proxy-headers: true

---
# LOCAL CONFIGURATION
spring:
    profiles: local
      


      
security:
  oauth2:
    client:
      clientId: openIdDemo
      clientSecret: 085a6d9e-d6f0-470f-b913-6760b4f7648c
      accessTokenUri: http://localhost:4000/auth/realms/demo/protocol/openid-connect/token
      userAuthorizationUri: http://localhost:4000/auth/realms/demo/protocol/openid-connect/auth
    resource:
       userInfoUri: http://localhost:4000/auth/realms/demo/protocol/openid-connect/userinfo      
       preferTokenInfo: false  
  sessions: ALWAYS

endpoints.routes.sensitive: false
       
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG      
      
---
# DOCKER CONFIGURATION
spring:
    profiles: docker
---
spring:
    profiles: no-security
    h2.console.enabled: true

security.ignored: /**    