# GLOBAL CONFIGURATION
spring:
    # if you want to set a different profile
    # use environment variable:
    #
    # SPRING_PROFILES_ACTIVE=docker
    profiles.active: local
    application.name: Zuul

# zuul proxy exposes 8082
server.port: 8082

# zuul routes
zuul:
  ignoredServices: '*'
  routes:
    user:
      path: /api/user_service/**
      url: http://localhost:8870/
#      sensitiveHeaders: 
      add-proxy-headers: true
    admin:
      path: /api/animad-service-administration/**
      url: http://localhost:39146/
#      sensitiveHeaders: 
      add-proxy-headers: true

---
# LOCAL CONFIGURATION
spring:
    profiles: local
      


      
security:
  oauth2:
    client:
      clientId: openIdDemo
      clientSecret: b0c2bbe0-ba2f-454c-85ad-59a08cc09e6c
      accessTokenUri: http://localhost:8080/auth/realms/demo/protocol/openid-connect/token
      userAuthorizationUri: http://localhost:8080/auth/realms/demo/protocol/openid-connect/auth
    resource:
      jwt:
        key-value: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqjrVO6S3X8U79FSJgY/zKBvEe+YOYAVRnjeaZLaFs66Amglf1RLp1G2ZANCtEV35uPOWi3ErkQDvGEOn0BNlgxYFI6iPO2co6RnPIRNEIhp7uvw9mxevXmIcRfv0/bulus81ET7H/POYqYpr7zXaN1EQU5nhjsSF39AHC5Xp49Fve8fihtWu63JOd/WnlkxJ+esxl+q+Wx1wBKdY8eaIxrKs3REZV0wxrSq7qwBEgAJ5HAojz3SO/A6s4K/J0Fm1WCxsnkm9LJ+gtnfDltYoJDbZafQyifT45oHz0pApIScqbsvgriOjQxSrQ7XzUx9btMxoKdPHrjlTukGweInqlQIDAQAB
       
  sessions: ALWAYS

endpoints.routes.sensitive: false
       
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG      
      
---
# DOCKER CONFIGURATION
spring:
    profiles: docker
---
spring:
    profiles: no-security
    h2.console.enabled: true

security.ignored: /**    
